services:
  server:
    build: server
    command: python3 /usr/server.py
    networks:
      default:
        ipv4_address: 172.16.238.2
    ports:
      - "12123:12123"
    healthcheck:
      test: ["CMD-SHELL", " netstat -an | grep -q 12123"]
    environment:
      LISTEN_PORT: 12123

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"
