version: "3"
services:
  server:
    build: server
    command: python3 /usr/server.py
    networks:
      default:
        ipv4_address: 172.16.238.2
    ports:
      - "12123:12123"
    healthcheck:
      test: ["CMD-SHELL", " netstat -an | grep -q 12123"]

  client:
    build: client
    command: python3 /usr/client.py
    networks:
      default:
        ipv4_address: 172.16.238.3
    depends_on:
      server:
        condition: service_healthy
    stdin_open: true
    tty: true

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"
