version: "3"
services:
  server:
    build: server
    command: python3 /usr/server.py
    ports:
      - "12123:12123"

  client:
    build: client
    command: python3 /usr/client.py
    network_mode: host
    depends_on:
      - server
    stdin_open: true
    tty: true
