name: CI workflow
on: push
jobs:
  flake8-lint:
    name: Flake8 check
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v3
      - name: Set up python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Flake8 lint check
        uses: py-actions/flake8@v2

  editorconfig-check:
    name: Check the editorconfig file
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
