name: CI workflow
on: push
jobs:
  flake8-lint:
    name: Flake8 Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Flake8 lint check
        uses: py-actions/flake8@v2

  makrdown-checker:
    name: Markdown Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run the Check
        run: npx markdown-cli *.md

  build-and-push:
    name: Build and Push the Docker Container
    needs: [ sonarcloud, snyk ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scrape_store_server:latest

  snyk:
    name: Snyk check
    needs: [ flake8-lint, makrdown-checker ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Snyk
        working-directory: ${{github.workspace}}
        run: |
          pip install -r server/requirements.txt
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --all-projects --detection-depth=3

  sonarcloud:
    name: SonarCloud check
    needs: [ flake8-lint, makrdown-checker ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
